//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.235
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLiblet.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NLiblet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cannot cast array item at {0}. Cannot cast &apos;{1}&apos; type instance to &apos;{2}&apos; type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CastCode_CannotCastArrayItemAt {
            get {
                return ResourceManager.GetString("CastCode_CannotCastArrayItemAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot cast array item at {0}. Cannot cast &apos;{1}&apos; type instance to &apos;{2}&apos; type with TypeConverter &apos;{3}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CastCode_CannotCastArrayItemWithTypeConverterAt {
            get {
                return ResourceManager.GetString("CastCode_CannotCastArrayItemWithTypeConverterAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot cast &apos;{0}&apos; type instance to &apos;{1}&apos; type with TypeConverter &apos;{2}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CastCode_CannotCastWithTypeConverter {
            get {
                return ResourceManager.GetString("CastCode_CannotCastWithTypeConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown primitive type &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CastCode_UnknownPrimitive {
            get {
                return ResourceManager.GetString("CastCode_UnknownPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input sequence ended unexpctedly at position {0:###,0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InputHexCharacterSequenceIsEndUnexpctedly {
            get {
                return ResourceManager.GetString("Error_InputHexCharacterSequenceIsEndUnexpctedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid code point : 0x{0:x4} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidCodePoint {
            get {
                return ResourceManager.GetString("Error_InvalidCodePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character &apos;{0:m}&apos;(\\u{0:x}, {0:c}) at position {1:###,0} is invalid as hexadecimal. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidHexCharacter {
            get {
                return ResourceManager.GetString("Error_InvalidHexCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot resolve overload between &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GeneratedCodeHelper_CannotResolveOverload {
            get {
                return ResourceManager.GetString("GeneratedCodeHelper_CannotResolveOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type of argument at {0} is value type ({1}), so it cannot be null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GeneratedCodeHelper_ValueTypeArgumentCannotBeNull {
            get {
                return ResourceManager.GetString("GeneratedCodeHelper_ValueTypeArgumentCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are too many parameters for method &apos;[{0}]{1}::{2}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MethodInfoExtensions_TooManyParameters {
            get {
                return ResourceManager.GetString("MethodInfoExtensions_TooManyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reflection_CustomMethodBaseIsNotSupported {
            get {
                return ResourceManager.GetString("Reflection_CustomMethodBaseIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type initializer (also known as static constructor or class initializer) is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reflection_TypeInitializerIsNotSupported {
            get {
                return ResourceManager.GetString("Reflection_TypeInitializerIsNotSupported", resourceCulture);
            }
        }
    }
}
