//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.237
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLiblet.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NLiblet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Strings are different at index {1}.{0}Expected:&apos;{2:e}&apos;(\\u{2:U}, {2:c}, {2:b}){0}Actual  :&apos;{3:e}&apos;(\\u{3:U}, {3:c}, {3:b}){0}Expected string :{7}{4:e}{8}{0}Actual string   :{7}{5:e}{8}{0}                 {6}^ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringDifference_DifferentAt {
            get {
                return ResourceManager.GetString("StringDifference_DifferentAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected is not null, but actual is null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringDifference_ExpectedIsNotNullButActualIsNull {
            get {
                return ResourceManager.GetString("StringDifference_ExpectedIsNotNullButActualIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected is null, but actual is not null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringDifference_ExpectedIsNullButActualIsNotNull {
            get {
                return ResourceManager.GetString("StringDifference_ExpectedIsNullButActualIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strings length are different.{0}Expected :{1:###,0}{0}Actual   :{2:###,0}{0}Expected string :{6}{3:e}{7}{0}Actual string   :{8}{4:e}{9}{0}                 {5}^ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringDifference_LengthAreNotEqual {
            get {
                return ResourceManager.GetString("StringDifference_LengthAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected is &lt;null&gt; but actual is &apos;{0}&apos;({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_ActualIsNotNull {
            get {
                return ResourceManager.GetString("XmlAssert_ActualIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected is &apos;{0}&apos;({1}) but actual is &lt;null&gt;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_ActualIsNull {
            get {
                return ResourceManager.GetString("XmlAssert_ActualIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Node #{1} are not equal.{0}XPath: {2}{0}Expected:&lt;null&gt;{0}Actual:{0}&quot;{3}&quot;({4}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_ActualNodeIsNotNull {
            get {
                return ResourceManager.GetString("XmlAssert_ActualNodeIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attribute &apos;{1}&apos; does not exist.{0}XPath: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_AttributeDoesNotExist {
            get {
                return ResourceManager.GetString("XmlAssert_AttributeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attribute names are not equal. {1}{0}XPath: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_AttributeNamesAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_AttributeNamesAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attribute values are not equal. {1}{0}XPath: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_AttributeValuesAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_AttributeValuesAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Node &apos;{1}&apos;({2}) at #{3} does not exist.{0}XPath: {4} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_ChildNodeDoesNotExist {
            get {
                return ResourceManager.GetString("XmlAssert_ChildNodeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1}{0}Node #{2} are not equal. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_ChildNodesAssertionTemplate {
            get {
                return ResourceManager.GetString("XmlAssert_ChildNodesAssertionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comments are not equal. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_CommentAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_CommentAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data of instruction are not equal. Expected is &apos;{0}&apos; but actual is &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_DataOfInstructionAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_DataOfInstructionAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Element names are not equal. {1}{0}XPath: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_ElementNamesAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_ElementNamesAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encoding of declaration are not equal. Expected is &apos;{0}&apos; but actual is &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_EncodingOfDeclarationAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_EncodingOfDeclarationAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Node #{1} nodes are not equal.{0}XPath: {1}{0}Expected:&quot;{3}&quot;({4}){0}Actual:{0}&lt;null&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_ExpectedNodeIsNotNull {
            get {
                return ResourceManager.GetString("XmlAssert_ExpectedNodeIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal subset of DTD are not equal. Expected is &apos;{0}&apos; but actual is &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_InternalSubsetOfDtdAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_InternalSubsetOfDtdAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name of DTD are not equal. Expected is &apos;{0}&apos; but actual is &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_NameOfDtdAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_NameOfDtdAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Node #{1} are not equal.{0}XPath: {2}{0}Expected:&quot;{3}&quot;({4}){0}Actual:{0}&quot;{5}&quot;({6}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_NodesAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_NodesAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Public ID of DTD are not equal. Expected is &apos;{0}&apos; but actual is &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_PublicIdOfDtdAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_PublicIdOfDtdAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some extra attributes exist. {1}{0}XPath: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_SomeExtraAttributesExist {
            get {
                return ResourceManager.GetString("XmlAssert_SomeExtraAttributesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some extra nodes exist from #{2}  &apos;{1}&apos;{0}XPath: {3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_SomeExtraChildNodesExist {
            get {
                return ResourceManager.GetString("XmlAssert_SomeExtraChildNodesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standalone of declaration are not equal. Expected is &apos;{0}&apos; but actual is &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_StandaloneOfDeclarationAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_StandaloneOfDeclarationAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System ID of DTD are not equal. Expected is &apos;{0}&apos; but actual is &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_SystemIdOfDtdAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_SystemIdOfDtdAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target of instruction are not equal. Expected is &apos;{0}&apos; but actual is &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_TargetOfInstructionAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_TargetOfInstructionAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text are not equal. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_TextAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_TextAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version of declaration are not equal. Expected is &apos;{0}&apos; but actual is &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_VersionOfDeclarationAreNotEqual {
            get {
                return ResourceManager.GetString("XmlAssert_VersionOfDeclarationAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (CData) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_XPathLabelCData {
            get {
                return ResourceManager.GetString("XmlAssert_XPathLabelCData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Comment) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_XPathLabelComment {
            get {
                return ResourceManager.GetString("XmlAssert_XPathLabelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (TextContent) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_XPathLabelTextContent {
            get {
                return ResourceManager.GetString("XmlAssert_XPathLabelTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (unknown) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlAssert_XPathLabelUnknown {
            get {
                return ResourceManager.GetString("XmlAssert_XPathLabelUnknown", resourceCulture);
            }
        }
    }
}
