//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.235
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLiblet.Text {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedBlockName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedBlockName() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NLiblet.Text.LocalizedBlockName", typeof(LocalizedBlockName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Aegean Numbers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Aegean_Numbers {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Aegean_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alchemical Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Alchemical_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Alchemical_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alphabetic Presentation Forms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Alphabetic_Presentation_Forms {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Alphabetic_Presentation_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ancient Greek Musical Notation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Ancient_Greek_Musical_Notation {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Ancient_Greek_Musical_Notation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ancient Greek Numbers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Ancient_Greek_Numbers {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Ancient_Greek_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ancient Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Ancient_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Ancient_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arabic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Arabic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arabic Presentation Forms-A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Arabic_Presentation_Forms_A {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Arabic_Presentation_Forms_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arabic Presentation Forms-B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Arabic_Presentation_Forms_B {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Arabic_Presentation_Forms_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arabic Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Arabic_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Arabic_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Armenian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Armenian {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Armenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arrows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Arrows {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avestan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Avestan {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Avestan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Balinese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Balinese {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Balinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bamum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Bamum {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Bamum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bamum Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Bamum_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Bamum_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basic Latin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Basic_Latin {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Basic_Latin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batak に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Batak {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Batak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bengali に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Bengali {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Bengali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block Elements に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Block_Elements {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Block_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bopomofo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Bopomofo {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Bopomofo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bopomofo Extended に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Bopomofo_Extended {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Bopomofo_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Box Drawing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Box_Drawing {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Box_Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brahmi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Brahmi {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Brahmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Braille Patterns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Braille_Patterns {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Braille_Patterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buginese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Buginese {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Buginese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buhid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Buhid {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Buhid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Byzantine Musical Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Byzantine_Musical_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Byzantine_Musical_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Carian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Carian {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Carian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cham に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Cham {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Cham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cherokee に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Cherokee {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Cherokee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CJK Compatibility に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_CJK_Compatibility {
            get {
                return ResourceManager.GetString("UnicoceBlockName_CJK_Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CJK Compatibility Forms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_CJK_Compatibility_Forms {
            get {
                return ResourceManager.GetString("UnicoceBlockName_CJK_Compatibility_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CJK Compatibility Ideographs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_CJK_Compatibility_Ideographs {
            get {
                return ResourceManager.GetString("UnicoceBlockName_CJK_Compatibility_Ideographs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CJK Compatibility Ideographs Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_CJK_Compatibility_Ideographs_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_CJK_Compatibility_Ideographs_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CJK Radicals Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_CJK_Radicals_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_CJK_Radicals_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CJK Strokes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_CJK_Strokes {
            get {
                return ResourceManager.GetString("UnicoceBlockName_CJK_Strokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CJK Symbols and Punctuation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_CJK_Symbols_and_Punctuation {
            get {
                return ResourceManager.GetString("UnicoceBlockName_CJK_Symbols_and_Punctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CJK Unified Ideographs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_CJK_Unified_Ideographs {
            get {
                return ResourceManager.GetString("UnicoceBlockName_CJK_Unified_Ideographs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CJK Unified Ideographs Extension A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_CJK_Unified_Ideographs_Extension_A {
            get {
                return ResourceManager.GetString("UnicoceBlockName_CJK_Unified_Ideographs_Extension_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CJK Unified Ideographs Extension B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_CJK_Unified_Ideographs_Extension_B {
            get {
                return ResourceManager.GetString("UnicoceBlockName_CJK_Unified_Ideographs_Extension_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CJK Unified Ideographs Extension C に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_CJK_Unified_Ideographs_Extension_C {
            get {
                return ResourceManager.GetString("UnicoceBlockName_CJK_Unified_Ideographs_Extension_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CJK Unified Ideographs Extension D に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_CJK_Unified_Ideographs_Extension_D {
            get {
                return ResourceManager.GetString("UnicoceBlockName_CJK_Unified_Ideographs_Extension_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combining Diacritical Marks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Combining_Diacritical_Marks {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Combining_Diacritical_Marks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combining Diacritical Marks for Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Combining_Diacritical_Marks_for_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Combining_Diacritical_Marks_for_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combining Diacritical Marks Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Combining_Diacritical_Marks_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Combining_Diacritical_Marks_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combining Half Marks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Combining_Half_Marks {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Combining_Half_Marks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common Indic Number Forms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Common_Indic_Number_Forms {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Common_Indic_Number_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control Pictures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Control_Pictures {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Control_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coptic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Coptic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Coptic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Counting Rod Numerals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Counting_Rod_Numerals {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Counting_Rod_Numerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cuneiform に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Cuneiform {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Cuneiform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cuneiform Numbers and Punctuation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Cuneiform_Numbers_and_Punctuation {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Cuneiform_Numbers_and_Punctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Currency Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Currency_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Currency_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cypriot Syllabary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Cypriot_Syllabary {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Cypriot_Syllabary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cyrillic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Cyrillic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Cyrillic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cyrillic Extended-A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Cyrillic_Extended_A {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Cyrillic_Extended_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cyrillic Extended-B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Cyrillic_Extended_B {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Cyrillic_Extended_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cyrillic Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Cyrillic_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Cyrillic_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deseret に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Deseret {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Deseret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Devanagari に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Devanagari {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Devanagari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Devanagari Extended に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Devanagari_Extended {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Devanagari_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dingbats に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Dingbats {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Dingbats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Domino Tiles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Domino_Tiles {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Domino_Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Egyptian Hieroglyphs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Egyptian_Hieroglyphs {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Egyptian_Hieroglyphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emoticons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Emoticons {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Emoticons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enclosed Alphanumeric Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Enclosed_Alphanumeric_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Enclosed_Alphanumeric_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enclosed Alphanumerics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Enclosed_Alphanumerics {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Enclosed_Alphanumerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enclosed CJK Letters and Months に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Enclosed_CJK_Letters_and_Months {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Enclosed_CJK_Letters_and_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enclosed Ideographic Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Enclosed_Ideographic_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Enclosed_Ideographic_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ethiopic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Ethiopic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Ethiopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ethiopic Extended に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Ethiopic_Extended {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Ethiopic_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ethiopic Extended-A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Ethiopic_Extended_A {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Ethiopic_Extended_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ethiopic Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Ethiopic_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Ethiopic_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Punctuation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_General_Punctuation {
            get {
                return ResourceManager.GetString("UnicoceBlockName_General_Punctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geometric Shapes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Geometric_Shapes {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Geometric_Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Georgian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Georgian {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Georgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Georgian Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Georgian_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Georgian_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Glagolitic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Glagolitic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Glagolitic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gothic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Gothic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Gothic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Greek and Coptic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Greek_and_Coptic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Greek_and_Coptic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Greek Extended に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Greek_Extended {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Greek_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gujarati に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Gujarati {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Gujarati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gurmukhi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Gurmukhi {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Gurmukhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Halfwidth and Fullwidth Forms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Halfwidth_and_Fullwidth_Forms {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Halfwidth_and_Fullwidth_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hangul Compatibility Jamo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Hangul_Compatibility_Jamo {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Hangul_Compatibility_Jamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hangul Jamo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Hangul_Jamo {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Hangul_Jamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hangul Jamo Extended-A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Hangul_Jamo_Extended_A {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Hangul_Jamo_Extended_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hangul Jamo Extended-B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Hangul_Jamo_Extended_B {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Hangul_Jamo_Extended_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hangul Syllables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Hangul_Syllables {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Hangul_Syllables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hanunoo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Hanunoo {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Hanunoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hebrew に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Hebrew {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Hebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High Private Use Surrogates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_High_Private_Use_Surrogates {
            get {
                return ResourceManager.GetString("UnicoceBlockName_High_Private_Use_Surrogates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High Surrogates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_High_Surrogates {
            get {
                return ResourceManager.GetString("UnicoceBlockName_High_Surrogates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiragana に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Hiragana {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Hiragana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ideographic Description Characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Ideographic_Description_Characters {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Ideographic_Description_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Imperial Aramaic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Imperial_Aramaic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Imperial_Aramaic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inscriptional Pahlavi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Inscriptional_Pahlavi {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Inscriptional_Pahlavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inscriptional Parthian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Inscriptional_Parthian {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Inscriptional_Parthian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IPA Extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_IPA_Extensions {
            get {
                return ResourceManager.GetString("UnicoceBlockName_IPA_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Javanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Javanese {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Javanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaithi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Kaithi {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Kaithi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kana Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Kana_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Kana_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kanbun に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Kanbun {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Kanbun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kangxi Radicals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Kangxi_Radicals {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Kangxi_Radicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kannada に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Kannada {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Kannada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Katakana に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Katakana {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Katakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Katakana Phonetic Extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Katakana_Phonetic_Extensions {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Katakana_Phonetic_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayah Li に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Kayah_Li {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Kayah_Li", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kharoshthi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Kharoshthi {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Kharoshthi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Khmer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Khmer {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Khmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Khmer Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Khmer_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Khmer_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lao に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Lao {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Lao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latin-1 Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Latin_1_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Latin_1_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latin Extended-A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Latin_Extended_A {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Latin_Extended_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latin Extended Additional に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Latin_Extended_Additional {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Latin_Extended_Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latin Extended-B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Latin_Extended_B {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Latin_Extended_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latin Extended-C に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Latin_Extended_C {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Latin_Extended_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latin Extended-D に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Latin_Extended_D {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Latin_Extended_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lepcha に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Lepcha {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Lepcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Letterlike Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Letterlike_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Letterlike_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Limbu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Limbu {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Limbu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Linear B Ideograms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Linear_B_Ideograms {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Linear_B_Ideograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Linear B Syllabary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Linear_B_Syllabary {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Linear_B_Syllabary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lisu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Lisu {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Lisu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low Surrogates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Low_Surrogates {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Low_Surrogates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lycian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Lycian {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Lycian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lydian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Lydian {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Lydian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mahjong Tiles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Mahjong_Tiles {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Mahjong_Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Malayalam に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Malayalam {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Malayalam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mandaic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Mandaic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Mandaic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mathematical Alphanumeric Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Mathematical_Alphanumeric_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Mathematical_Alphanumeric_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mathematical Operators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Mathematical_Operators {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Mathematical_Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meetei Mayek に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Meetei_Mayek {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Meetei_Mayek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miscellaneous Mathematical Symbols-A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Miscellaneous_Mathematical_Symbols_A {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Miscellaneous_Mathematical_Symbols_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miscellaneous Mathematical Symbols-B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Miscellaneous_Mathematical_Symbols_B {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Miscellaneous_Mathematical_Symbols_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miscellaneous Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Miscellaneous_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Miscellaneous_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miscellaneous Symbols and Arrows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Miscellaneous_Symbols_and_Arrows {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Miscellaneous_Symbols_and_Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miscellaneous Symbols And Pictographs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Miscellaneous_Symbols_And_Pictographs {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Miscellaneous_Symbols_And_Pictographs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miscellaneous Technical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Miscellaneous_Technical {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Miscellaneous_Technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modifier Tone Letters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Modifier_Tone_Letters {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Modifier_Tone_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mongolian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Mongolian {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Mongolian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Musical Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Musical_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Musical_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Myanmar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Myanmar {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Myanmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Myanmar Extended-A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Myanmar_Extended_A {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Myanmar_Extended_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Tai Lue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_New_Tai_Lue {
            get {
                return ResourceManager.GetString("UnicoceBlockName_New_Tai_Lue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NKo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_NKo {
            get {
                return ResourceManager.GetString("UnicoceBlockName_NKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number Forms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Number_Forms {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Number_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ogham に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Ogham {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Ogham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ol Chiki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Ol_Chiki {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Ol_Chiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old Italic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Old_Italic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Old_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old Persian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Old_Persian {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Old_Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old South Arabian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Old_South_Arabian {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Old_South_Arabian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old Turkic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Old_Turkic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Old_Turkic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optical Character Recognition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Optical_Character_Recognition {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Optical_Character_Recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oriya に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Oriya {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Oriya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Osmanya に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Osmanya {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Osmanya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phags-pa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Phags_pa {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Phags_pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phaistos Disc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Phaistos_Disc {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Phaistos_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phoenician に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Phoenician {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Phoenician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phonetic Extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Phonetic_Extensions {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Phonetic_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phonetic Extensions Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Phonetic_Extensions_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Phonetic_Extensions_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playing Cards に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Playing_Cards {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Playing_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Private Use Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Private_Use_Area {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Private_Use_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rejang に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Rejang {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Rejang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rumi Numeral Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Rumi_Numeral_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Rumi_Numeral_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Runic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Runic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Runic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Samaritan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Samaritan {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Samaritan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saurashtra に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Saurashtra {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Saurashtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shavian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Shavian {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Shavian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sinhala に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Sinhala {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Sinhala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Small Form Variants に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Small_Form_Variants {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Small_Form_Variants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spacing Modifier Letters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Spacing_Modifier_Letters {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Spacing_Modifier_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specials に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Specials {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sundanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Sundanese {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Sundanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Superscripts and Subscripts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Superscripts_and_Subscripts {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Superscripts_and_Subscripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supplemental Arrows-A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Supplemental_Arrows_A {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Supplemental_Arrows_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supplemental Arrows-B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Supplemental_Arrows_B {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Supplemental_Arrows_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supplemental Mathematical Operators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Supplemental_Mathematical_Operators {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Supplemental_Mathematical_Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supplemental Punctuation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Supplemental_Punctuation {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Supplemental_Punctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supplementary Private Use Area-A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Supplementary_Private_Use_Area_A {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Supplementary_Private_Use_Area_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supplementary Private Use Area-B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Supplementary_Private_Use_Area_B {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Supplementary_Private_Use_Area_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Syloti Nagri に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Syloti_Nagri {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Syloti_Nagri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Syriac に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Syriac {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Syriac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tagalog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Tagalog {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Tagalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tagbanwa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Tagbanwa {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Tagbanwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Tags {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tai Le に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Tai_Le {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Tai_Le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tai Tham に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Tai_Tham {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Tai_Tham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tai Viet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Tai_Viet {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Tai_Viet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tai Xuan Jing Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Tai_Xuan_Jing_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Tai_Xuan_Jing_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tamil に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Tamil {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Tamil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telugu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Telugu {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Telugu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thaana に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Thaana {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Thaana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thai に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Thai {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tibetan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Tibetan {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Tibetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tifinagh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Tifinagh {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Tifinagh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transport And Map Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Transport_And_Map_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Transport_And_Map_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ugaritic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Ugaritic {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Ugaritic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unified Canadian Aboriginal Syllabics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Unified_Canadian_Aboriginal_Syllabics {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Unified_Canadian_Aboriginal_Syllabics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unified Canadian Aboriginal Syllabics Extended に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Unified_Canadian_Aboriginal_Syllabics_Extended {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Unified_Canadian_Aboriginal_Syllabics_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vai に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Vai {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Vai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variation Selectors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Variation_Selectors {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Variation_Selectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variation Selectors Supplement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Variation_Selectors_Supplement {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Variation_Selectors_Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vedic Extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Vedic_Extensions {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Vedic_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical Forms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Vertical_Forms {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Vertical_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yi Radicals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Yi_Radicals {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Yi_Radicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yi Syllables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Yi_Syllables {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Yi_Syllables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yijing Hexagram Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnicoceBlockName_Yijing_Hexagram_Symbols {
            get {
                return ResourceManager.GetString("UnicoceBlockName_Yijing_Hexagram_Symbols", resourceCulture);
            }
        }
    }
}
